name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt Main
    - name: Issue assigner
      uses: estrada9166/issue-assigner@v1
      #with:
        # The GITHUB_TOKEN secret
        #GITHUB_TOKEN: # optional
        # Create comments with the commit information
        #WITH_COMMENTS: # optional, default is true
